# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.menstrual_tracker: debug

menstrual_tracker:
  last_period_start: "2025-08-01"
  cycle_length: 28
  period_length: 5
